services:
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=prod
    restart: always
    networks:
      - app-network
  frontend:
    build: frontend
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
