services:
  backend:
    image: vietbac2002/retail-store-backend:latest
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=prod
    restart: always
    networks:
      - app-network
  frontend:
    image: vietbac2002/retail-store-frontend:latest
    ports:
      - 80:80
    depends_on:
      - backend
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
